CREATE TABLE "it3b-api-key-secondweb_cart" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "it3b-api-key-secondweb_cart_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"userId" varchar(255) NOT NULL,
	"itemId" varchar(255) NOT NULL,
	"name" varchar(255) NOT NULL,
	"period" varchar(255),
	"origin" varchar(255),
	"value" integer NOT NULL,
	"quantity" integer DEFAULT 1,
	"imageUrl" varchar(500),
	"createdAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);
--> statement-breakpoint
CREATE TABLE "it3b-api-key-secondweb_orders" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "it3b-api-key-secondweb_orders_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"orderId" varchar(255) NOT NULL,
	"userId" varchar(255) NOT NULL,
	"items" jsonb NOT NULL,
	"total" integer NOT NULL,
	"shippingData" jsonb NOT NULL,
	"paymentMethod" varchar(255) NOT NULL,
	"estimatedDelivery" varchar(255),
	"status" varchar(100) DEFAULT 'pending',
	"createdAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	CONSTRAINT "it3b-api-key-secondweb_orders_orderId_unique" UNIQUE("orderId")
);
--> statement-breakpoint
CREATE TABLE "it3b-api-key-secondweb_payments" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "it3b-api-key-secondweb_payments_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"paymentId" varchar(255) NOT NULL,
	"orderId" varchar(255) NOT NULL,
	"method" varchar(255) NOT NULL,
	"amount" integer NOT NULL,
	"status" varchar(100) DEFAULT 'processing',
	"transactionData" jsonb,
	"createdAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	CONSTRAINT "it3b-api-key-secondweb_payments_paymentId_unique" UNIQUE("paymentId")
);
--> statement-breakpoint
CREATE INDEX "cart_user_idx" ON "it3b-api-key-secondweb_cart" USING btree ("userId");--> statement-breakpoint
CREATE INDEX "order_user_idx" ON "it3b-api-key-secondweb_orders" USING btree ("userId");--> statement-breakpoint
CREATE INDEX "payment_order_idx" ON "it3b-api-key-secondweb_payments" USING btree ("orderId");