CREATE TABLE "it3b-api-key-secondweb_cart_items" (
	"id" serial PRIMARY KEY NOT NULL,
	"user_id" varchar(255),
	"item_name" varchar(255) NOT NULL,
	"image_url" varchar(1024),
	"quantity" integer DEFAULT 1 NOT NULL,
	"price" numeric(10, 2) NOT NULL,
	"created_at" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);
--> statement-breakpoint
CREATE TABLE "it3b-api-key-secondweb_post" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "it3b-api-key-secondweb_post_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" varchar(256),
	"createdAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"updatedAt" timestamp with time zone
);
--> statement-breakpoint
ALTER TABLE "it3b-api-key-secondweb_cart" DISABLE ROW LEVEL SECURITY;--> statement-breakpoint
DROP TABLE "it3b-api-key-secondweb_cart" CASCADE;--> statement-breakpoint
ALTER TABLE "it3b-api-key-secondweb_orders" DROP CONSTRAINT "it3b-api-key-secondweb_orders_orderId_unique";--> statement-breakpoint
ALTER TABLE "it3b-api-key-secondweb_payments" DROP CONSTRAINT "it3b-api-key-secondweb_payments_paymentId_unique";--> statement-breakpoint
DROP INDEX "order_user_idx";--> statement-breakpoint
DROP INDEX "payment_order_idx";--> statement-breakpoint
ALTER TABLE "it3b-api-key-secondweb_orders" ALTER COLUMN "total" SET DATA TYPE numeric(10, 2);--> statement-breakpoint
ALTER TABLE "it3b-api-key-secondweb_orders" ALTER COLUMN "status" SET DATA TYPE varchar(50);--> statement-breakpoint
ALTER TABLE "it3b-api-key-secondweb_orders" ALTER COLUMN "status" SET DEFAULT 'Pending';--> statement-breakpoint
ALTER TABLE "it3b-api-key-secondweb_orders" ALTER COLUMN "status" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "it3b-api-key-secondweb_payments" ALTER COLUMN "id" SET DATA TYPE serial;--> statement-breakpoint
ALTER TABLE "it3b-api-key-secondweb_payments" ALTER COLUMN "id" DROP IDENTITY;--> statement-breakpoint
ALTER TABLE "it3b-api-key-secondweb_payments" ALTER COLUMN "method" SET DATA TYPE varchar(100);--> statement-breakpoint
ALTER TABLE "it3b-api-key-secondweb_payments" ALTER COLUMN "amount" SET DATA TYPE numeric(10, 2);--> statement-breakpoint
ALTER TABLE "it3b-api-key-secondweb_payments" ALTER COLUMN "status" SET DATA TYPE varchar(50);--> statement-breakpoint
ALTER TABLE "it3b-api-key-secondweb_payments" ALTER COLUMN "status" SET DEFAULT 'Completed';--> statement-breakpoint
ALTER TABLE "it3b-api-key-secondweb_payments" ALTER COLUMN "status" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "it3b-api-key-secondweb_orders" ADD COLUMN "order_id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL;--> statement-breakpoint
ALTER TABLE "it3b-api-key-secondweb_orders" ADD COLUMN "user_id" varchar(255);--> statement-breakpoint
ALTER TABLE "it3b-api-key-secondweb_orders" ADD COLUMN "payment_method" varchar(100) NOT NULL;--> statement-breakpoint
ALTER TABLE "it3b-api-key-secondweb_orders" ADD COLUMN "shipping_data" jsonb;--> statement-breakpoint
ALTER TABLE "it3b-api-key-secondweb_orders" ADD COLUMN "created_at" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL;--> statement-breakpoint
ALTER TABLE "it3b-api-key-secondweb_payments" ADD COLUMN "order_id" uuid NOT NULL;--> statement-breakpoint
ALTER TABLE "it3b-api-key-secondweb_payments" ADD COLUMN "transaction_id" varchar(255);--> statement-breakpoint
ALTER TABLE "it3b-api-key-secondweb_payments" ADD COLUMN "created_at" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL;--> statement-breakpoint
CREATE INDEX "name_idx" ON "it3b-api-key-secondweb_post" USING btree ("name");--> statement-breakpoint
ALTER TABLE "it3b-api-key-secondweb_payments" ADD CONSTRAINT "it3b-api-key-secondweb_payments_order_id_it3b-api-key-secondweb_orders_order_id_fk" FOREIGN KEY ("order_id") REFERENCES "public"."it3b-api-key-secondweb_orders"("order_id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "it3b-api-key-secondweb_orders" DROP COLUMN "id";--> statement-breakpoint
ALTER TABLE "it3b-api-key-secondweb_orders" DROP COLUMN "orderId";--> statement-breakpoint
ALTER TABLE "it3b-api-key-secondweb_orders" DROP COLUMN "userId";--> statement-breakpoint
ALTER TABLE "it3b-api-key-secondweb_orders" DROP COLUMN "items";--> statement-breakpoint
ALTER TABLE "it3b-api-key-secondweb_orders" DROP COLUMN "shippingData";--> statement-breakpoint
ALTER TABLE "it3b-api-key-secondweb_orders" DROP COLUMN "paymentMethod";--> statement-breakpoint
ALTER TABLE "it3b-api-key-secondweb_orders" DROP COLUMN "estimatedDelivery";--> statement-breakpoint
ALTER TABLE "it3b-api-key-secondweb_orders" DROP COLUMN "createdAt";--> statement-breakpoint
ALTER TABLE "it3b-api-key-secondweb_payments" DROP COLUMN "paymentId";--> statement-breakpoint
ALTER TABLE "it3b-api-key-secondweb_payments" DROP COLUMN "orderId";--> statement-breakpoint
ALTER TABLE "it3b-api-key-secondweb_payments" DROP COLUMN "transactionData";--> statement-breakpoint
ALTER TABLE "it3b-api-key-secondweb_payments" DROP COLUMN "createdAt";