import "~/styles/globals.css";
import { type Metadata } from "next";
import { Geist } from "next/font/google";
import { ClerkProvider } from "@clerk/nextjs";
import { TopNav } from "./_components/topnav";

export const metadata: Metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

const geist = Geist({
  subsets: ["latin"],
  variable: "--font-geist-sans",
});

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <ClerkProvider publishableKey={process.env.NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY}>
      <html lang="en" className={geist.variable}>
        <body className="min-h-screen text-yellow-100 relative">
          {/* Background without blur */}
          <div
            className="fixed inset-0 bg-cover bg-center -z-10"
            
          />

          {/* Optional darker overlay for readability */}
          <div className="fixed inset-0 bg-black/30 -z-10" />

          {/* Content */}
          <TopNav />
          {children}
        </body>
      </html>
    </ClerkProvider>
  );
}
